### ISSUE TITLE
missing nova client module

### ISSUE THREAD

**Issue by JAORMX** [rcritten/novajoin#1]
in the create route of the join controller, there is an attempt to get the nova instance from an ID, however, this is done via the NovaClient [1] class which is supposed to be in a module that creates it[2]. This module wasn't included in the source.

[1] https://github.com/rcritten/novajoin/blob/master/novajoin/join.py#L198
[2] https://github.com/rcritten/novajoin/blob/master/novajoin/join.py#L27

**Comment by JAORMX** [comment]
Addressing it with https://github.com/rcritten/novajoin/pull/2

**Comment by rcritten** [comment]
Yeah, I goofed and forgot to git add it. I tested using a tarball created out of the same directory which is why my off-machine tests worked. I'll push up a fix soon.

**Comment by rcritten** [comment]
Fixed in 6c4ef8298bbdf48f82d13fb25a0f3958237392f2
